/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CivilianRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.GroceriesOrganization;
import Business.Organization.Organization;
import Business.Supplies.Groceries;
import Business.Supplies.GroceriesDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GroceriesWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajw
 */
public class GroceryShoppingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroceryShoppingJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private GroceriesDirectory groceriesDirectory;
    private UserAccount account;
    private GroceriesOrganization groceriesOrganization;
    public GroceryShoppingJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system, GroceriesOrganization groceriesOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.groceriesDirectory = groceriesDirectory;
        this.system = system;
        this.account = account;
        this.groceriesOrganization = groceriesOrganization;
        System.out.println("Debug inside Groceries Shopping constructor");
        System.out.println(groceriesOrganization);
//        System.out.println(organization);
        populateGroceriesTable();
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groceriesJTable = new javax.swing.JTable();
        quantityBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        requestGroceriesBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        addDeliveryBackBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groceriesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Description"
            }
        ));
        jScrollPane1.setViewportView(groceriesJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 630, 117));

        quantityBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", " " }));
        quantityBox.setToolTipText("");
        quantityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBoxActionPerformed(evt);
            }
        });
        add(quantityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel1.setText("Quantity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        requestGroceriesBtn.setBackground(new java.awt.Color(0, 0, 51));
        requestGroceriesBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        requestGroceriesBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestGroceriesBtn.setText("Place Order");
        requestGroceriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestGroceriesBtnActionPerformed(evt);
            }
        });
        add(requestGroceriesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 30));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Product Name", "Price", "Quantity", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 630, 97));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 30));

        addDeliveryBackBtn.setBackground(new java.awt.Color(0, 0, 51));
        addDeliveryBackBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addDeliveryBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        addDeliveryBackBtn.setText("<<Back");
        addDeliveryBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeliveryBackBtnActionPerformed(evt);
            }
        });
        add(addDeliveryBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void quantityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBoxActionPerformed

    public void populateGroceriesTable(){
        DefaultTableModel groceriesModel = (DefaultTableModel) groceriesJTable.getModel();
        groceriesModel.setRowCount(0);
//        System.out.println("inside populateMenuTable---2---");
//        groceriesDirectory.getGroceries_Directory();
//        System.out.println("inside populateMenuTable---3---");
        for(Groceries item: system.getgD().getGroceries_Directory()){
//                    System.out.println("inside for loop ---3---");
                    Object[] row = new Object[3];
                    row[0] = item; 
                    row[1] = item.getProductPrice();
                    row[2] = item.getProductDescription();
                    groceriesModel.addRow(row);
        }
    
    }
            
    public boolean isUniqueProduct(String productName){
        for(WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            if(String.valueOf(request.getClass()).equalsIgnoreCase("class Business.WorkQueue.GroceriesWorkRequest")){
                System.out.println(request);
                if(((GroceriesWorkRequest) request).getProductName().equalsIgnoreCase(productName)){
                    return false;
                }
            }
        }
        return true;
    }
    
    
    
    private void requestGroceriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestGroceriesBtnActionPerformed
        // TODO add your handling code here:
        int row = groceriesJTable.getSelectedRow();
        System.out.println("Groceries shopping row"+String.valueOf(row));
        int count = groceriesJTable.getSelectedRowCount();
        System.out.println("Groceries shopping row"+String.valueOf(count));
        Groceries groceries = (Groceries) groceriesJTable.getModel().getValueAt(row, 0);
//                .getDataVector().elementAt(row);
//                .getValueAt(row, 0);
        
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            
            if(!isUniqueProduct(groceries.getProductName())){
                JOptionPane.showMessageDialog(null, "You have already requested for this product. If you want to modify it, please delete it and add again.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int quantity = Integer.parseInt(quantityBox.getSelectedItem().toString());
            GroceriesWorkRequest groceriesRequest = new GroceriesWorkRequest();
            groceriesRequest.setSender(account);
            groceriesRequest.setStatus("Sent");
            groceriesRequest.setProductName(groceries.getProductName());
            groceriesRequest.setProductPrice(groceries.getProductPrice());
            groceriesRequest.setQuantity(quantity);
            
            Organization org = null;

            for (Network network : system.getNetworkList()) {
                //Step 2.a: check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);

                    //Step 3:check against each organization for each enterprise
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof GroceriesOrganization) {
                            org = organization;
                            break;
                        }

                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(groceriesRequest);
                System.out.println("Added Request to Org ");
                account.getWorkQueue().getWorkRequestList().add(groceriesRequest);
                System.out.println("Added Request to UserAccount ");
//            dB4OUtil.storeSystem(system);
//            System.out.println("Stored Inside System");
            }
            populateRequestTable();
            JOptionPane.showMessageDialog(null, "Request Has Been Raised. You will be notified accordingly.", "Warning", JOptionPane.WARNING_MESSAGE);
//            populateRequestTable();
        }
//        if(count == 1){
//            if(row >= 0){
//                int quantity = Integer.parseInt(quantityBox.getSelectedItem().toString());
//                Restaurant restaurant = restaurantDirectory.getRestaurant(menuDirectory.getFoodItemByIndex(row).getRestaurantId());
//                Customer customer = customerDirectory.getCustomer(userAccount.getEmployee().getName());
//                FoodItem foodItem = menuDirectory.getFoodItemByIndex(row);
//                String status = "Awaiting Order Confirmation";
//
//                Order orderRequest = business.getOrderDirectory().addOrder();
//                orderRequest.setOrderId("O"+(business.getOrderDirectory().getOrderDirectory().size()));
//                orderRequest.setOrderStatusPercentage(25);
//                orderRequest.setFoodItem(foodItem);
//                orderRequest.setRestaurant(restaurant);
//                orderRequest.setCustomer(customer);
//                orderRequest.setQuantity(quantity);
//                orderRequest.setMessage("Order has been placed");
//                orderRequest.setSender(userAccount);
//                orderRequest.setStatus(status);
//                business.getWorkQueue().getWorkRequestList().add(orderRequest);
//                JOptionPane.showMessageDialog(null, "Your Order has been sucessfully placed!");
//                populateRequestTable();
//            }
//        }
//        else{
//            JOptionPane.showMessageDialog(null, "Please select one row!");
//        }

    }//GEN-LAST:event_requestGroceriesBtnActionPerformed

    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        System.out.println(groceriesOrganization);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            if (request instanceof GroceriesWorkRequest)
            {
                Object[] row = new Object[7];
                row[0] = request;
                row[1] = ((GroceriesWorkRequest) request).getProductName();
                row[2] = ((GroceriesWorkRequest) request).getProductPrice();
                row[3] = ((GroceriesWorkRequest) request).getQuantity();
                row[4] = request.getSender().getEmployee().getName();
                row[5] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                row[6] = request.getStatus();
            
                model.addRow(row);
            }
        }    
    
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addDeliveryBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeliveryBackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        StoreManagementJPanel manageMenuJPanel = (StoreManagementJPanel) component;
        //        manageMenuJPanel.populate();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_addDeliveryBackBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = workRequestJTable.getSelectedRow();
//        System.out.println("Groceries shopping row"+String.valueOf(row));
        int count = workRequestJTable.getSelectedRowCount();
//        System.out.println("Groceries shopping row"+String.valueOf(count));
        GroceriesWorkRequest groceryRequest = (GroceriesWorkRequest) workRequestJTable.getModel().getValueAt(row, 0);
        account.getWorkQueue().getWorkRequestList().remove(groceryRequest);
        populateRequestTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeliveryBackBtn;
    private javax.swing.JTable groceriesJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox quantityBox;
    private javax.swing.JButton requestGroceriesBtn;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
