/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacistRole;


import Business.EcoSystem;
import static Business.Organization.Organization.Type.Groceries;
import Business.Supplies.GroceriesDirectory;
import Business.Supplies.Groceries;
import Business.Supplies.Medicine;
import Business.Supplies.MedicineDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author prajw
 */
public class AddMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicine
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private MedicineDirectory medicineDirectory;
//    private RestaurantDirectory restaurantDirectory;
//    private MenuDirectory menuDirectory;
    private UserAccount account;
    public AddMedicineJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system, MedicineDirectory medicineDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.medicineDirectory = medicineDirectory;
        this.system = system;
//        this.menuDirectory = menuDirectory;
        this.account = account;
//        System.out.println("Before populate menu table --1--");
        populateMenuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        medManufacturerTF = new javax.swing.JTextField();
        medNameTF = new javax.swing.JTextField();
        medPriceTF = new javax.swing.JTextField();
        addMedJTable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medJTable = new javax.swing.JTable();

        jLabel1.setText("Product Manufacturer");

        jLabel2.setText("Product Name");

        jLabel3.setText("Product Price");

        medNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medNameTFActionPerformed(evt);
            }
        });

        addMedJTable.setText("Add Medicine");
        addMedJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedJTableActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        medJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Description"
            }
        ));
        jScrollPane1.setViewportView(medJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(228, 228, 228)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(medPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addMedJTable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(82, 82, 82)
                                .addComponent(medManufacturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medManufacturerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(addMedJTable)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateMenuTable(){
        DefaultTableModel model = (DefaultTableModel) medJTable.getModel();
        model.setRowCount(0);
        System.out.println("inside populateMenuTable---2---");
//        groceriesDirectory.getGroceries_Directory();
        System.out.println("inside populateMenuTable---3---");
        for(Medicine item: system.getmD().getMedicine_Directory()){
//                    System.out.println("inside for loop ---3---");
                    Object[] row = new Object[3];
                    row[0] = item;
                    row[1] = item.getMedPrice();
                    row[2] = item.getMedManufacturer();
                    model.addRow(row);
        }
    }
    
    private void addMedJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedJTableActionPerformed
        // TODO add your handling code here:
        String name = medNameTF.getText();
        String manufacturer = medManufacturerTF.getText();
        double price = 0.0;
        try {
            price = Double.parseDouble(medPriceTF.getText());
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Enter valid price!");
        }
        if(name.isEmpty() || manufacturer.isEmpty() || price == 0.0 ){
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
        else if(!system.getmD().checkIfNameIsUnique(name)){
            JOptionPane.showMessageDialog(null, "Product already added!");
        }
        else{
            //            String restaurantId = account.getEmployee().getName();
            system.getmD().add(name,String.valueOf(price),manufacturer);
            JOptionPane.showMessageDialog(null, "Medicine added!");
            medNameTF.setText("");
            medManufacturerTF.setText("");
            medPriceTF.setText("");
            populateMenuTable();
        }
    }//GEN-LAST:event_addMedJTableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        StoreManagementJPanel manageMenuJPanel = (StoreManagementJPanel) component;
        //        manageMenuJPanel.populate();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void medNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medNameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medJTable;
    private javax.swing.JTextField medManufacturerTF;
    private javax.swing.JTextField medNameTF;
    private javax.swing.JTextField medPriceTF;
    // End of variables declaration//GEN-END:variables
}
