/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.BookingDirectory;
import Business.TravelAgencyDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author paipr
 */
public class TravelAgencyUser extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgencyUser
     */
     JPanel right_Panel;
     TravelAgencyDirectory travel_dir;
     AirlinerDirectory airline_Dir;
     BookingDirectory booking_dir;
    public TravelAgencyUser(JPanel RightPanel,TravelAgencyDirectory travel_dir,String optionvalue,AirlinerDirectory airline_Dir, BookingDirectory booking_dir) {
        initComponents();
        this.right_Panel=RightPanel;
        this.travel_dir = travel_dir;
        this.airline_Dir = airline_Dir;
        this.booking_dir=booking_dir;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JToggleButton();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister);
        btnRegister.setBounds(379, 185, 135, 69);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(379, 291, 135, 69);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Travel Agency User ");
        add(jLabel1);
        jLabel1.setBounds(322, 29, 236, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/195314.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-520, -210, 1780, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
         TravelAgencyRegister panel = new TravelAgencyRegister(right_Panel, travel_dir);
        right_Panel.add("TravelAgencyRegister", panel);
        CardLayout cardlayout = (CardLayout) right_Panel.getLayout();
        cardlayout.next(right_Panel);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        TravelAgencyLogin panel = new TravelAgencyLogin(right_Panel,travel_dir, travel_dir.getTravelAgencyList(),airline_Dir,booking_dir);
        right_Panel.add("TravelAgencyLogin", panel);
        CardLayout cardlayout = (CardLayout) right_Panel.getLayout();
        cardlayout.next(right_Panel);
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
