/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GroceryStoreManagerRole;

import Business.EcoSystem;
import static Business.Organization.Organization.Type.Groceries;
import Business.Supplies.GroceriesDirectory;
import Business.Supplies.Groceries;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajw
 */
public class AddGroceryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddGroceryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private GroceriesDirectory groceriesDirectory;
//    private RestaurantDirectory restaurantDirectory;
//    private MenuDirectory menuDirectory;
    private UserAccount account;
    public AddGroceryJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system, GroceriesDirectory groceriesDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.groceriesDirectory = groceriesDirectory;
        this.system = system;
//        this.menuDirectory = menuDirectory;
        this.account = account;
//        System.out.println("Before populate menu table --1--");
        populateMenuTable();
//        System.out.println(system.getgD().getGroceries_Directory());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productDescTF = new javax.swing.JTextField();
        productNameTF = new javax.swing.JTextField();
        productPriceTF = new javax.swing.JTextField();
        addProductJTable = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Product Description");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Product Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Product Price");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        productDescTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDescTFActionPerformed(evt);
            }
        });
        add(productDescTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 130, 30));
        add(productNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 30));
        add(productPriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 30));

        addProductJTable.setBackground(new java.awt.Color(0, 0, 51));
        addProductJTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addProductJTable.setForeground(new java.awt.Color(255, 255, 255));
        addProductJTable.setText("Add Product");
        addProductJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductJTableActionPerformed(evt);
            }
        });
        add(addProductJTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 110, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 40));

        productJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Description"
            }
        ));
        jScrollPane1.setViewportView(productJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 540, 170));
    }// </editor-fold>//GEN-END:initComponents

    public void populateMenuTable(){
        DefaultTableModel model = (DefaultTableModel) productJTable.getModel();
        model.setRowCount(0);
        System.out.println("inside populateMenuTable---2---");
//        groceriesDirectory.getGroceries_Directory();
        System.out.println("inside populateMenuTable---3---");
        for(Groceries item: system.getgD().getGroceries_Directory()){
//                    System.out.println("inside for loop ---3---");
                    Object[] row = new Object[3];
                    row[0] = item; 
                    row[1] = item.getProductPrice();
                    row[2] = item.getProductDescription();
                    model.addRow(row);
        }
    }
    
    
    private void addProductJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJTableActionPerformed
        // TODO add your handling code here:
        String name = productNameTF.getText();
        String description = productDescTF.getText();
        double price = 0.0;
        try {
            price = Double.parseDouble(productPriceTF.getText());
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Enter valid price!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        if(name.isEmpty() || description.isEmpty() || price == 0.0 ){
            JOptionPane.showMessageDialog(null, "Enter all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(!system.getgD().checkIfNameIsUnique(name)){
            JOptionPane.showMessageDialog(null, "Product already added!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
//            String restaurantId = account.getEmployee().getName();
            system.getgD().add(name,String.valueOf(price),description);
            JOptionPane.showMessageDialog(null, "Food Item added to Menu!");
            productNameTF.setText("");
            productDescTF.setText("");
            productPriceTF.setText("");
            populateMenuTable();
        }
    }//GEN-LAST:event_addProductJTableActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        StoreManagementJPanel manageMenuJPanel = (StoreManagementJPanel) component;
//        manageMenuJPanel.populate();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void productDescTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDescTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productDescTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productDescTF;
    private javax.swing.JTable productJTable;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JTextField productPriceTF;
    // End of variables declaration//GEN-END:variables
}
