/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Civilian.CivilianDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccountDirectory;
import Business.Civilian.Civilian;
import Business.Employee.Employee;
import Business.Role.CivilianRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author paipr
 */
public class RegisterCivilianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterCivilianJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
//    private CivilianDirectory cd;
    private UserAccountDirectory user_dir;
    private UserAccount account;
    
    public RegisterCivilianJPanel(JPanel userProcessContainer, EcoSystem ecosystem, CivilianDirectory cd, UserAccountDirectory user_dir, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = ecosystem;
//        this.cd = cd;
//        this.user_dir = user_dir;
        this.account = account; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        BtnRegister = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        ContactNo = new javax.swing.JLabel();
        txtContactNO = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register a Civilian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 67, -1, -1));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 123, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 163, -1, -1));

        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 203, -1, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 120, 231, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 160, 231, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 200, 231, -1));

        jLabel5.setText("Sex:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 243, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Prefer not to Answer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 240, 231, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Enter Credentials");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 393, -1, -1));

        jLabel7.setText("User Name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 430, -1, -1));

        jLabel8.setText("Password:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 462, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 427, 228, -1));

        BtnRegister.setBackground(new java.awt.Color(0, 0, 51));
        BtnRegister.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Register");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 495, -1, 35));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 459, 228, -1));

        ContactNo.setText("Contact No:");
        add(ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 283, -1, -1));

        txtContactNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNOActionPerformed(evt);
            }
        });
        add(txtContactNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 280, 231, -1));

        jLabel18.setText("Address:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 323, -1, -1));
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 320, 229, -1));

        backJButton.setBackground(new java.awt.Color(0, 0, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 494, -1, 36));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
        char[] passwordCharArray = jPasswordField1.getPassword();
        String password = String.valueOf(passwordCharArray);
          String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String age = txtAge.getText();
        String sex = (String) jComboBox1.getSelectedItem();
        String username = txtUserName.getText();
        String contactNo=txtContactNO.getText();
        String address=txtaddress.getText();
        
        if (txtFirstName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " First Name can't be empty");
            return;
        }
        if (txtLastName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Last Name can't be empty");
            return;
        }
        if (txtUserName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " User Name can't be empty");
            return;
        }
         
            if(!system.getUserAccountDirectory().checkIfUsernameIsUnique(username)){
            JOptionPane.showMessageDialog(null, "Username already exists!");
    return;
            }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(null, " Password can't be empty");
            return;
        }
        if (usernamePatternCorrect()==false){
  
    txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
    JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
    return;
} else{
   
    txtUserName.setBorder(BorderFactory.createLineBorder(Color.black));
}
if (passwordPatternCorrect()==false){
 
    jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED));
    JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
    return;
}else{
    
    jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.black));
}
        if (txtaddress.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Address can't be empty");
            return;
        }
          if (txtContactNO.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Contact Number can't be empty");
            return;}
          
         if(!phoneFormat(contactNo))
        {
            JOptionPane.showMessageDialog(null, "Contact Number format is incorrect!");
            return;
        }
       
          
          
        try {
            if (!txtAge.getText().equals("")) {
                Integer.parseInt(txtAge.getText());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Age cannot be String");
            return;
        }
        
       

//        Civilian c = system.getCd().addCivilian();
//        system.getUserAccountDirectory().createUserAccount(txtUserName.getText(), password);
//        c.setFirstName(txtFirstName.getText());
//        c.setLastName(txtLastName.getText());
//        c.setAge(txtAge.getText());
//        c.setSex((String) jComboBox1.getSelectedItem());
//        c.setUsername(txtUserName.getText());
//        c.setPassword(password);
       
        
        
        
        
      

        Employee employee = system.getEmployeeDirectory().createEmployee(firstName);
        UserAccount account = system.getUserAccountDirectory().createUserAccount(txtUserName.getText(), password, employee, new CivilianRole());
        Civilian c = system.getCd().createCivilian(firstName, lastName, age, sex, account, username, contactNo, address);
         JOptionPane.showMessageDialog(null, " User Registered successfully!");
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        

        txtUserName.setText("");
        jPasswordField1.setText("");
        txtContactNO.setText("");
        txtaddress.setText("");
        

    }//GEN-LAST:event_BtnRegisterActionPerformed
public boolean phoneFormat(String contactNo){
        String regex = "^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(contactNo);
        if(matcher.matches()){
            return true;
        }
        return false;
    }

private boolean usernamePatternCorrect(){
        Pattern pat=Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m=pat.matcher(txtUserName.getText());
        boolean boo=m.matches();
        return boo;
    }
    
     private boolean passwordPatternCorrect(){
        Pattern pat1;
        pat1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1=pat1.matcher(jPasswordField1.getText());
        boolean bat1=m1.matches();
        return bat1;
    }
    private void txtContactNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNOActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegister;
    private javax.swing.JLabel ContactNo;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContactNO;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtaddress;
    // End of variables declaration//GEN-END:variables
}
