/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GroceryStoreManagerRole;

import java.awt.CardLayout;
import Business.EcoSystem;
import Business.Organization.GroceriesOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.Supplies.GroceriesDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GroceriesWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajw
 */
public class StoreManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StoreManagementJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private GroceriesOrganization groceriesOrganization;
    private Organization org;
    private GroceriesDirectory groceriesDirectory;
    
    public StoreManagementJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.groceriesOrganization = (GroceriesOrganization)organization;
        System.out.println("Debug inside storeManagement constructor.");
        System.out.println(organization);
        this.org = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageOrdersBtn = new javax.swing.JButton();
        manageProductsBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageOrdersBtn.setText("Manage Orders");
        manageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersBtnActionPerformed(evt);
            }
        });
        add(manageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, 40));

        manageProductsBtn.setText("Manage Products");
        manageProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsBtnActionPerformed(evt);
            }
        });
        add(manageProductsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersBtnActionPerformed
        // TODO add your handling code here:
        StoreManagerWorkAreaJPanel processWorkRequestJPanel = new StoreManagerWorkAreaJPanel( userProcessContainer,  userAccount,  org,  business);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageOrdersBtnActionPerformed

    private void manageProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsBtnActionPerformed
        // TODO add your handling code here:
        AddGroceryJPanel addProductJPanel = new AddGroceryJPanel(userProcessContainer,userAccount, business,  groceriesDirectory);
        userProcessContainer.add("addProductJPanel", addProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageOrdersBtn;
    private javax.swing.JButton manageProductsBtn;
    // End of variables declaration//GEN-END:variables
}
