/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nitya
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
 private UserAccount userAccount;
 private EcoSystem system;
    private Enterprise enterprise;
   private HospitalOrganization organization;

    public HospitalAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,HospitalOrganization organization,Enterprise enterprise, EcoSystem system ) {
          initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        
    }
    /**
     * Creates new form HospitalAdmin
     */
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestTestBtn = new javax.swing.JButton();
        ReqConttracingBtn = new javax.swing.JButton();

        RequestTestBtn.setText("Request Test");
        RequestTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestTestBtnActionPerformed(evt);
            }
        });

        ReqConttracingBtn.setText("Request Contact Tracing");
        ReqConttracingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReqConttracingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(ReqConttracingBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(RequestTestBtn)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(RequestTestBtn)
                .addGap(55, 55, 55)
                .addComponent(ReqConttracingBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RequestTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestTestBtnActionPerformed
        // TODO add your handling code here:
        
         RequestTestWorkAreaJPanel panel = new RequestTestWorkAreaJPanel(userProcessContainer, 
           userAccount,
            organization,
            enterprise, 
            system);
        userProcessContainer.add("RequestTestWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_RequestTestBtnActionPerformed

    private void ReqConttracingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReqConttracingBtnActionPerformed
        // TODO add your handling code here:
         RequestContactTracingJPanel panel = new RequestContactTracingJPanel(userProcessContainer, 
           userAccount,
        organization,
            enterprise, 
            system);
        userProcessContainer.add("RequestContactTracingJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_ReqConttracingBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReqConttracingBtn;
    private javax.swing.JButton RequestTestBtn;
    // End of variables declaration//GEN-END:variables
}
