/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Civilian.CivilianDirectory;
import Business.EcoSystem;
import Business.Civilian.Civilian;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignWardWorkRequest;
import Business.WorkQueue.IsolationWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author paipr
 */
public class ProcessIsolationRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private IsolationWorkRequest request;
    private EcoSystem system;
    private UserAccount account;
    /**
     * Creates new form ProcessIsolationRequestJPanel
     */
    public ProcessIsolationRequestJPanel(JPanel userProcessContainer, UserAccount account,IsolationWorkRequest request, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = ecosystem;
        this.account = account;
//        CivilianDirectory cd = system.getCd();
        String civilianName = "";
        String civilianAge = "";
        String civilianSex = "";
        for (Civilian c : system.getCd().getCivilianList()) {
            if (c.getUsername().equals(request.getSender().getUsername())) {
                civilianName = c.getFirstName()+ " "+ c.getLastName();
                civilianAge = c.getAge();
                civilianSex = c.getSex();
                
                break;

            }
        }
        
        String symptom1 = ((IsolationWorkRequest)request).getSymptom1();
        String symptom2 = ((IsolationWorkRequest)request).getSymptom2();
        String symptom3 = ((IsolationWorkRequest)request).getSymptom3();
        String symptom4 = ((IsolationWorkRequest)request).getSymptom4();
        String symptom5 = ((IsolationWorkRequest)request).getSymptom5();
        String comments = ((IsolationWorkRequest)request).getComment();
        String symptoms = ((IsolationWorkRequest)request).getSymptoms();
        
        
        lblSymptoms.setText(symptoms.substring(0,symptoms.length() - 1) + ".");
        lblName.setText(civilianName);
        lblAge.setText(civilianAge);
        lblComments.setText(comments);
        lblSex.setText(civilianSex);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_Comments = new javax.swing.JTextArea();
        lbl = new javax.swing.JLabel();
        txtArea_analysis = new javax.swing.JTextField();
        BtnHospital = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Process Isolation Request:");

        jLabel2.setText("Patient Name:");

        jLabel3.setText("Symptoms:");

        jLabel4.setText("Comments:");

        jLabel5.setText("Age:");

        jLabel6.setText("Sex:");

        jButton1.setText("Back");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Doctor Analysis:");

        jLabel8.setText("Comments:");

        txtArea_Comments.setColumns(20);
        txtArea_Comments.setRows(5);
        jScrollPane1.setViewportView(txtArea_Comments);

        lbl.setText("Analysis:");

        BtnHospital.setText("Redirect to Hospital");
        BtnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHospitalActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblName.setText("jLabel9");

        lblAge.setText("jLabel10");

        lblSex.setText("jLabel11");

        lblSymptoms.setText("jLabel12");

        lblComments.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblName))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblComments)
                                    .addComponent(lblSymptoms)
                                    .addComponent(lblSex))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl)
                                        .addGap(54, 54, 54)
                                        .addComponent(txtArea_analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(39, 39, 39)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnHospital)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(70, 70, 70))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72)
                        .addComponent(lblAge)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblSex))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblSymptoms))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblComments)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl)
                            .addComponent(txtArea_analysis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHospital)
                    .addComponent(jButton3))
                .addGap(194, 194, 194))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHospitalActionPerformed
        // TODO add your handling code here:
        
        String civilianName = "";
        String civilianAge = "";
        String civilianSex = "";
        
        for (Civilian c : system.getCd().getCivilianList()) {
            System.out.println("printing username");
            if (c.getUsername().equals(request.getSender().getUsername())) {
                civilianName = c.getFirstName()+ " "+ c.getLastName();
                civilianAge = c.getAge();
                civilianSex = c.getSex();
                
                break;

            }
        }
        
        AssignWardWorkRequest request = new AssignWardWorkRequest();
        
        request.setAnalysis(txtArea_analysis.getText());
        if(txtArea_analysis.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Doctor Analysis can't be empty");
             return;
         }
        request.setStatus("Sent");
//        request.setMessage(lblMainConcern.getText());
        request.setSender(account);
        request.setName(civilianName);
        ///////////////////////////////////////////////
        request.setComments(txtArea_Comments.getText());
        if(txtArea_analysis.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Doctor Comments can't be empty");
             return;
         }
        
         Organization org = null;

        for (Network network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                //                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);

                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof HospitalOrganization) {
                        org = organization;
                        break;
                    }

                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Added Request to Org ");
            account.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Added Request to UserAccount ");
            
            
            
        }
        
    }//GEN-LAST:event_BtnHospitalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHospital;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JTextArea txtArea_Comments;
    private javax.swing.JTextField txtArea_analysis;
    // End of variables declaration//GEN-END:variables
}
