/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.Civilian.Civilian;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ContactTracingOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignWardWorkRequest;
import Business.WorkQueue.ContactTracingWorkRequest;
import Business.WorkQueue.IsolationWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.LabAssistantRole.LabAssistantWorkAreaJPanel;

/**
 *
 * @author paipr
 */
public class ProcessWardRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWardRequestJPanel
     */
    
    private JPanel userProcessContainer;
    private AssignWardWorkRequest request;
    private EcoSystem system;
    private UserAccount account;
    private String username;
    String civilianName = "";
        String civilianAge = "";
        String civilianSex = "";
        String firstName = "";
        String lastName = "";
        String address = "";
//        String age = "";
//        String sex = "";
        String contact = "";
    
    public ProcessWardRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem ecosystem, Organization organization, AssignWardWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = ecosystem;
        this.account = account;
        
//        String civilianName = "";
//        String civilianAge = "";
//        String civilianSex = "";
        for (Civilian c : system.getCd().getCivilianList()) {
//            System.out.println("Printing from process ward req loop");
//            System.out.println(c.getFirstName()+ " "+ c.getLastName());
//            System.out.println(request.getName());
            if ((c.getFirstName()+ " "+ c.getLastName()).equals(request.getName())) {
                civilianName = c.getFirstName()+ " "+ c.getLastName();
                civilianAge = c.getAge();
                civilianSex = c.getSex();
                firstName = c.getFirstName();
                lastName = c.getLastName();
//                civilianAge = c.getAge();
//                civilianSex = c.getSex();
                address = c.getAddress();
                contact = c.getContactNo();
                
                break;

            }
        }

        lblName.setText(civilianName);
        lblAge.setText(civilianAge);
        lblSex.setText(civilianSex);
        
//        lblAnalysis.setText(((AssignWardWorkRequest)request).getAnalysis());
//        lblComments.setText(((AssignWardWorkRequest)request).getComments());
        
        ((AssignWardWorkRequest)request).setIsolationWard(100);
        ((AssignWardWorkRequest)request).setNormalWard(100);
        ((AssignWardWorkRequest)request).setIcuWard(100);
        
        this.username = ((AssignWardWorkRequest)request).getUsername();
        remainingWards();
        
//        ((AssignWardWorkRequest)request).setTraced("No");
        if(((AssignWardWorkRequest)request).getTraced().equalsIgnoreCase("yes")){
        
            lblContactTracing.setText("Contact traced!");
            BtnAssign.setEnabled(false);
//            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnAssign = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        cboxIsolation = new javax.swing.JCheckBox();
        cboxNormal = new javax.swing.JCheckBox();
        cboxIcu = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblIsolation = new javax.swing.JLabel();
        lblNormal = new javax.swing.JLabel();
        lblIcu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblContactTracing = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Assign a Ward:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 11, -1, -1));

        jLabel4.setText("Patient Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 83, -1, -1));

        jLabel5.setText("Age:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 115, -1, -1));

        jLabel6.setText("Sex:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 148, -1, -1));

        BtnAssign.setText("Assign");
        BtnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAssignActionPerformed(evt);
            }
        });
        add(BtnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, 30));

        lblName.setText("jLabel7");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 83, -1, -1));

        lblAge.setText("jLabel8");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 115, -1, -1));

        lblSex.setText("jLabel9");
        add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 148, -1, -1));

        cboxIsolation.setText("Isolation Ward");
        add(cboxIsolation, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 104, -1, -1));

        cboxNormal.setText("Normal Ward");
        add(cboxNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 150, -1, -1));

        cboxIcu.setText("ICU");
        add(cboxIcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 191, -1, -1));

        jLabel12.setText("Remaining:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 108, -1, -1));

        jLabel13.setText("Remaining:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 154, -1, -1));

        jLabel14.setText("Remaining:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 195, -1, -1));

        lblIsolation.setText("jLabel15");
        add(lblIsolation, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 108, -1, -1));

        lblNormal.setText("jLabel16");
        add(lblNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 154, -1, -1));

        lblIcu.setText("jLabel17");
        add(lblIcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 195, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Contact Tracing");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 11, -1, -1));

        jButton2.setText("Initiate Contact Tracing");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 122, -1, -1));

        lblContactTracing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(lblContactTracing, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 175, 252, 54));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    public void remainingWards(){
        lblIsolation.setText(Integer.toString(((AssignWardWorkRequest)request).getIsolationWard()));
        lblNormal.setText(Integer.toString(((AssignWardWorkRequest)request).getNormalWard()));
        lblIcu.setText(Integer.toString(((AssignWardWorkRequest)request).getIcuWard()));
    }
    
    private void BtnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAssignActionPerformed
        // TODO add your handling code here:
        String ward = "";
        if (cboxIsolation.isSelected()){ward = cboxIsolation.getText(); ((AssignWardWorkRequest)request).updateIsolationWard(); remainingWards();};
        if (cboxNormal.isSelected()){ward = cboxNormal.getText();((AssignWardWorkRequest)request).updateNormalWard(); remainingWards();};
        if (cboxIcu.isSelected()){ward = cboxIcu.getText();((AssignWardWorkRequest)request).updateIcuWard(); remainingWards();};
        
        ((AssignWardWorkRequest)request).setWardAssigned("Yes");
        ((AssignWardWorkRequest)request).setWardType(ward);
        JOptionPane.showMessageDialog(null,"Assigned successfully!");
        
        
        
        
    }//GEN-LAST:event_BtnAssignActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        lblContactTracing.setText("Request Sent");
        
        ContactTracingWorkRequest request = new ContactTracingWorkRequest();
        
//         String civilianName = "";
//        String civilianAge = "";
//        String civilianSex = "";
//        String firstName = "";
//        String lastName = "";
//        String address = "";
////        String age = "";
////        String sex = "";
//        String contact = "";
//        
//        for (Civilian c : system.getCd().getCivilianList()) {
//            System.out.println("Printing from process ward req loop");
//            System.out.println(c.getFirstName()+ " "+ c.getLastName());
//            System.out.println(request.getName());
//            if ((c.getFirstName()+ " "+ c.getLastName()).equals(request.getName())) {
////                civilianName = c.getFirstName()+ " "+ c.getLastName();
//                firstName = c.getFirstName();
//                civilianAge = c.getAge();
//                civilianSex = c.getSex();
//                address = c.getAddress();
//                contact = c.getContactNo();
//                
//                break;
//
//            }
//        }
       System.out.println("printing while adding");
       System.out.println(firstName);
        request.setStatus("Sent");
//        request.setMessage(lblMainConcern.getText());
        request.setSender(account);
        request.setName(civilianName);
        request.setFirstName(firstName);
        request.setLastName(lastName);
        request.setAge(civilianAge);
        request.setSex(civilianSex);
        request.setAddress(address);
        request.setContactNo(contact);
        ///////////////////////////////////////////////
        
        
        request.setUsername(username);
         Organization org = null;

        for (Network network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                //                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);

                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof ContactTracingOrganization) {
                        org = organization;
                        break;
                    }

                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Added labtest Request to UserAccount "); 
            JOptionPane.showMessageDialog(null,"Contact tracing request initiated!");
            
        }
  
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        LabAssistantWorkAreaJPanel dwjp = (LabAssistantWorkAreaJPanel) component;
//        dwjp.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAssign;
    private javax.swing.JButton backJButton;
    private javax.swing.JCheckBox cboxIcu;
    private javax.swing.JCheckBox cboxIsolation;
    private javax.swing.JCheckBox cboxNormal;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContactTracing;
    private javax.swing.JLabel lblIcu;
    private javax.swing.JLabel lblIsolation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblSex;
    // End of variables declaration//GEN-END:variables
}
