/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelAgencyInterface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Booking;
import Business.BookingDirectory;
import Business.Customer;
import Business.TravelAgencyDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paipr
 */
public class TravelAgencyViewBooking extends javax.swing.JPanel {
private AirlinerDirectory airlinerDirectory;
    JPanel RightPanel;
    BookingDirectory booking_dir;
    Customer c;
    Booking b;
    TravelAgencyDirectory travel_dir;
    /**
     * Creates new form TA_ViewBooking
     */
    public TravelAgencyViewBooking(AirlinerDirectory airlinerDirectory, JPanel RightPanel,TravelAgencyDirectory travel_dir , BookingDirectory booking_dir) {
        initComponents();
        this.airlinerDirectory = airlinerDirectory;
        this.RightPanel = RightPanel;
        this.booking_dir = booking_dir;
        this.travel_dir=travel_dir;

        populate_Table();
    }
     public void populate_Table() {
        DefaultTableModel TBLmod = (DefaultTableModel) tblBooking.getModel();

        for (Booking b : booking_dir.getBookingList()) {

            if (b.getBookedBy().equalsIgnoreCase("TravelAgent")) {
                
                Object row[] = new Object[7];
                row[0] = b.getFullName();
                row[1] = b.getAirlinerName();
                row[2] = b.getFlightID();
                row[3] = b.getBookedSeats();
                row[4] = b.getSource();
                row[5] = b.getDestination();
                row[6] = b;
                
                

                TBLmod.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("   View All Bookings ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Airline Name", "Flight ID", "Seats", "Source", "Destination", "Booking"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBooking);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 730, 230));

        btnDelete.setBackground(new java.awt.Color(153, 0, 51));
        btnDelete.setText("Delete Booking");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        
        int row = tblBooking.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Booking to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        Booking book = (Booking) tblBooking.getValueAt(row, 6);
        booking_dir.removeBooking(book);
        populate_Table();
        JOptionPane.showMessageDialog(null, "Booking Deleted!", "Information", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBooking;
    // End of variables declaration//GEN-END:variables
}
