/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelAgencyInterface;

import Business.AirlinerDirectory;
import Business.Booking;
import Business.BookingDirectory;
import Business.Customer;
import Business.Flights;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author paipr
 */
public class TravelAgencyCustomerSeatBooking extends javax.swing.JPanel {

    private AirlinerDirectory airlinerDirectory;
    private Flights flights;
    JPanel RightPanel;
    ArrayList<String> tempBookedSeats;
    private BookingDirectory bookingList;

    /**
     * Creates new form TA_CustomerSeatBooking
     */
    public TravelAgencyCustomerSeatBooking(JPanel RightPanel, Flights flights, AirlinerDirectory airlinerDirectory, BookingDirectory booking_dir) {
        initComponents();
        this.RightPanel = RightPanel;
        this.flights = flights;
        this.airlinerDirectory = airlinerDirectory;
        this.bookingList = booking_dir;
        combobox_SeatingPreference.removeAllItems();
        this.tempBookedSeats = new ArrayList<>();

        for (String s : flights.getSeatList()) {
            combobox_SeatingPreference.addItem(s);
        }

        txt_FlightID.setText(flights.getFlightID());
        txt_Airliner.setText(flights.getAirlinerName());
        int total = flights.getTotalSeats();

        flights.setTotalSeats(total);
        txt_AvailableSeats.setText(String.valueOf(flights.getTotalSeats()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Airliner = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_FlightID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_AvailableSeats = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboboxgender = new javax.swing.JComboBox();
        txtPassport = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        combobox_SeatingPreference = new javax.swing.JComboBox();
        btnAddSeat = new javax.swing.JButton();
        txtSelectedSeats = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Seats for Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, -1));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 83, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));
        add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, -1));

        jLabel4.setText("Email ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setText("Airliner:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txt_Airliner.setEnabled(false);
        add(txt_Airliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, -1));

        jLabel6.setText("Flight ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        txt_FlightID.setEnabled(false);
        txt_FlightID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FlightIDActionPerformed(evt);
            }
        });
        add(txt_FlightID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, -1));

        jLabel9.setText("Available Seats:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        txt_AvailableSeats.setEnabled(false);
        txt_AvailableSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AvailableSeatsActionPerformed(evt);
            }
        });
        add(txt_AvailableSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 110, -1));

        jLabel7.setText("Gender:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        comboboxgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        comboboxgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxgenderActionPerformed(evt);
            }
        });
        add(comboboxgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 121, -1));
        add(txtPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 130, -1));

        jLabel8.setText("Passport:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel10.setText("Seating Preference:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        combobox_SeatingPreference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_SeatingPreferenceActionPerformed(evt);
            }
        });
        add(combobox_SeatingPreference, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 160, -1));

        btnAddSeat.setText("Add");
        btnAddSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSeatActionPerformed(evt);
            }
        });
        add(btnAddSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 80, -1));

        txtSelectedSeats.setEnabled(false);
        add(txtSelectedSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 360, 270, -1));

        btnBook.setBackground(new java.awt.Color(51, 204, 0));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txt_FlightIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FlightIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FlightIDActionPerformed

    private void txt_AvailableSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AvailableSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AvailableSeatsActionPerformed

    private void comboboxgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxgenderActionPerformed

    private void combobox_SeatingPreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_SeatingPreferenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_SeatingPreferenceActionPerformed

    private void btnAddSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSeatActionPerformed
        // TODO add your handling code here:

        String seat = (String) combobox_SeatingPreference.getSelectedItem();
        String tempSeat = seat;

        tempSeat = txtSelectedSeats.getText();

        if (!seat.equals(null) && !seat.equals("Window")) {
            System.out.println(seat);
            flights.removeSeat(seat);
            System.out.println("Seat Removed");

            if (seat.contains("1") || seat.contains("6")) {
                System.out.println("Window");

                tempSeat = tempSeat + " - Window";

            } else if ((seat.contains("2") || seat.contains("5"))) {
                System.out.println("Middle");

                tempSeat = tempSeat + " - Middle";
            } else if ((seat.contains("3") || seat.contains("4"))) {
                System.out.println("Aisle");

                tempSeat = tempSeat + " - Aisle";

            }

            combobox_SeatingPreference.removeAllItems();

            for (String s : flights.getSeatList()) {
                combobox_SeatingPreference.addItem(s);

            }

            tempBookedSeats.add(seat);

            System.out.println("Seat Added");

            txtSelectedSeats.setText(tempSeat);

        }


    }//GEN-LAST:event_btnAddSeatActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        try {
            if (txtFirstName.getText().equals("")
                    || txtLastName.getText().equals("")
                    || txtPassport.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please input all the fields");
            } else {

//                Customer c = airlinerDirectory.addCustomer();
//
//                c.setFirstName(txt_FirstName.getText());
//                c.setLastName(txt_LastName.getText());
//                c.setPassportNumber(txt_Passport.getText());
//                c.setFlightID(flights.getFlightID());
//                c.setAirlinerName(flights.getAirlinerName());
//                c.setEmailID(txt_EmailID.getText());
                //                ArrayList<String> seatsBooked;
                //                String seat = (String) combobox_SeatingPreference.getSelectedItem();
                //                if(!seat.equals(null)&& !seat.equals("Window"))
                //                {
                //                    System.out.println(seat);
                //                    flights.removeSeatFromSeatList(seat);
                //                    System.out.println("Seat Removed");
                //
                ////                    seatsBooked = c.getSeatsBooked();
                ////                    seatsBooked.add(seat);
                //
                ////                    System.out.println(seatsBooked);
                //
                ////                    c.setSeatsBooked(seatsBooked);
                //                    c.getBooked_Seats().add(seat);
                //
                //
                //                    System.out.println("Seat Added");
                //
                //                }
                Booking b = bookingList.addBooking();
                b.setEmailID(txtEmailID.getText());
                b.setFullName(txtFirstName.getText() + " " + txtLastName.getText());

                b.setAirlinerName(txt_Airliner.getText());
                b.setFlightID(txt_FlightID.getText());
                b.setAirlinerName(flights.getAirlinerName());
                b.setBookedBy("TravelAgent");
                b.setDepartureDate(flights.getDepartureTime());
                b.setDestination(flights.getDestination());
                b.setSource(flights.getSource());
                for (String s : tempBookedSeats) {

                    b.getBookedSeats().add(s);
                    flights.setTotalSeats(flights.getTotalSeats()- 1);
                    txt_AvailableSeats.setText(String.valueOf(flights.getTotalSeats()));

                }

                JOptionPane.showMessageDialog(null, "Seats have been booked!");
                txtPassport.setText("");
                txtSelectedSeats.setText("");
                txtFirstName.setText("");
                txtLastName.setText("");
                txtEmailID.setText("");

            }
        } catch (Exception e) {

            System.out.println(e);

            JOptionPane.showMessageDialog(null, "Please enter proper inputs");
        }
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSeat;
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox combobox_SeatingPreference;
    private javax.swing.JComboBox comboboxgender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtSelectedSeats;
    private javax.swing.JTextField txt_Airliner;
    private javax.swing.JTextField txt_AvailableSeats;
    private javax.swing.JTextField txt_FlightID;
    // End of variables declaration//GEN-END:variables
}
