/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.EcoSystem;
//import static Business.Organization.Organization.Type.Delivery;
import Business.Supplies.DeliveryManDirectory;
import Business.Supplies.DeliveryMan;
import Business.Supplies.DeliveryManDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prajw
 */
public class AddDeliveryMenJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDeliveryMenJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DeliveryManDirectory deliveryManDirectory;
    private UserAccount account;
    public AddDeliveryMenJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system, DeliveryManDirectory deliveryManDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.deliveryManDirectory = deliveryManDirectory;
        this.system = system;
        this.account = account;
//        System.out.println("Before populate menu table --1--");
//        populateDeliveryManTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgeTF = new javax.swing.JTextField();
        deliveryManNameTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        addProductJTable = new javax.swing.JButton();
        addDeliveryBackBtn = new javax.swing.JButton();

        jLabel1.setText("Age");

        jLabel2.setText("Delivery Man Name");

        jLabel3.setText("Phone Number");

        AgeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTFActionPerformed(evt);
            }
        });

        deliveryManNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryManNameTFActionPerformed(evt);
            }
        });

        addProductJTable.setText("Add Delivery Man");
        addProductJTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductJTableActionPerformed(evt);
            }
        });

        addDeliveryBackBtn.setText("Back");
        addDeliveryBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeliveryBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addDeliveryBackBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deliveryManNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(AgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(addProductJTable)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addDeliveryBackBtn)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryManNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(addProductJTable)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTFActionPerformed

//    public void populateDeliveryManTable(){
//        DefaultTableModel model = (DefaultTableModel) deliveryMenJTable.getModel();
//        model.setRowCount(0);
//        System.out.println("inside populateMenuTable---2---");
////        groceriesDirectory.getDeliveryMan_Directory();
//        System.out.println("inside populateMenuTable---3---");
//        for(DeliveryMan item: system.getDmd().getDeliveryMan_Directory()){
////                    System.out.println("inside for loop ---3---");
//                    Object[] row = new Object[3];
//                    row[0] = item; 
//                    row[1] = item.getPhoneNumber();
//                    row[2] = item.getAge();
//                    model.addRow(row);
//        }
//    }
    private void addProductJTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJTableActionPerformed
        // TODO add your handling code here:
        String name = deliveryManNameTF.getText();
        String age = AgeTF.getText();
        String phoneNumber = phoneNumberTF.getText();
        
//        try {
//            age Integer.parseInt(age);
//        }catch(NumberFormatException exception){
//            JOptionPane.showMessageDialog(null, "Enter valid price!");
//        }
        if(name.isEmpty() || age.isEmpty() || age.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
        else if(!phoneFormat(phoneNumber))
        {
            JOptionPane.showMessageDialog(null, "Phone format incorrect!");
        }
        else if(!system.getDmd().isPhoneUnique(phoneNumber)){
            JOptionPane.showMessageDialog(null, "Phone Number already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //            String restaurantId = account.getEmployee().getName();
            system.getDmd().add(name,phoneNumber,age);
            JOptionPane.showMessageDialog(null, "Delivery man added!");
            deliveryManNameTF.setText("");
            AgeTF.setText("");
            phoneNumberTF.setText("");
//            populateDeliveryManTable();
        }
    }//GEN-LAST:event_addProductJTableActionPerformed

    private void addDeliveryBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeliveryBackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        StoreManagementJPanel manageMenuJPanel = (StoreManagementJPanel) component;
        //        manageMenuJPanel.populate();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_addDeliveryBackBtnActionPerformed

    public boolean phoneFormat(String phone){
        String regex = "^\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$";
        Pattern pattern = Pattern.compile(regex);
        
        Matcher matcher = pattern.matcher(phone);
        if(matcher.matches()){
            return true;
        }
        return false;
    }
    
    private void deliveryManNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryManNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryManNameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeTF;
    private javax.swing.JButton addDeliveryBackBtn;
    private javax.swing.JButton addProductJTable;
    private javax.swing.JTextField deliveryManNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField phoneNumberTF;
    // End of variables declaration//GEN-END:variables
}
